### PR TITLE
Enhances function to work with spreadsheet that has no map_id field.

### LINKED ISSUE #85: Notice: Undefined index: map_id in profile page that has no map_id field
Some spreadsheet doesn't has the map, so it doesn't make sense to have the map_id in CSV file.  However, if there is no map_id, some errors occurred including the total number of record is not showed and link is broken, since those related to the map_id.
It was suggested to enhance the function for this.

### PR DESCRIPTION
**Pull request by Huyeng**
Enhances function to work with spreadsheet that has no map_id field.
Fixes #85

### CODE REVIEW

File: post-types/templates/page-profiles-list-page.php [hunk 1]
```diff
@@ -16,7 +16,17 @@
         <?php
           // Display Total list
           $show_total_value = "";
-          $array_map_profile = array_map(function($value){return array_key_exists('map_id', $value) ? $value['map_id'] : "";}, $profiles);
+          $array_map_profile = array();
```
Comment (acorbi) [inline post-types/templates/page-profiles-list-page.php]: @Huyeng I have added the creation of the **array_map_profile** and **id** variables outside the **if** clause. Variables should be initialized in the proper scope.
