### PR TITLE
[IMP] Fix error display on Frontend

### LINKED ISSUE #235: Error was spotted on the Frontend of Profile page
- [x] Incorrect display of Full Width Middle Content
- [x] Some input from the backend are not sanitized
- [x] Wrong Data Classification definition popup for 'Secondary Data Source' and 'Other Data'
- [x] Data Classification Definition popup doesn't display on some Profile page
- [x] Fixing some PHP warning and error (should be from PHP5 to PHP7)

### PR DESCRIPTION
**Pull request by S-mardii**
Fixed #235

### CODE REVIEW

File: post-types/profile-pages.php [hunk 1]
```diff
@@ -494,35 +494,35 @@ public function save_post_data($post_id)
                 }
 
                 if (isset($_POST['_csv_resource_url'])) {
-                    update_post_meta($post_id, '_csv_resource_url', $_POST['_csv_resource_url']);
+                    update_post_meta($post_id, '_csv_resource_url', esc_url_raw($_POST['_csv_resource_url']));
```
Comment (EricSoroos) [inline post-types/profile-pages.php:497]: Was this doing a stored XSS?

**Comment by EricSoroos** [comment]
This is on preprod.

**Comment by EricSoroos** [comment]
This is on prod now.
